### ISSUE TITLE
Classes & IDs

### ISSUE THREAD

**Issue by sophshep** [michelleling225/GitHub-Enterprise-Releases#1]
You are currently using a mix of classes (`.im-a-class`) and IDs (`#im-an-id`). We generally only use classes. There are some slight differences (too confusing to get into when you start), but it's a good habit to only use classes to begin with - this will make things less confusing in your HTML.

**Comment by michelleling225** [comment]
Ahhh. I see thanks sophie! Although, I was attempting to make my dropdown menu, and some of the code suggested using id instead. I'm not exactly sure why, but I also am not completely familiar with how Javascript and HTML fit together and am not comfortable enough to change it.
